# sample submit file

universe = docker
docker_image = bojunliu/ts-dart:3.0.0

log = job_$(Cluster)_$(Process).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

# Fill in with whatever executable you're using
executable = submit.sh 

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_input_files = ./

request_cpus = 1
request_memory = 50GB
request_disk = 10GB
queue 1
