attempt: '1'
trial: 1
num_trials: 5
num_states: 4
data_set_name: Slab Geometry
input_features: 131
feature_input_string: 131 features
learning_rate: 0.001
mode: regularize
batch_size: 1000
beta: 0.01
feat_dim: 3
pretrain: 10
n_epochs: 20
lagtime: 75
nn_structure:
- 131
- 125
- 100
- 75
- 50
- 25
- 3
random_seed: 1
